language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
  - cd frontend
  - npm install jspm
  - jspm config registries.github.auth $GITHUB_TOKEN
  - jspm init
  - ls -a app/jspm_packages
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
